services:
  postgres:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgressql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: